### ISSUE TITLE
Authenticated Endpoints

### ISSUE THREAD

**Issue by mackenziexD** [LaravelEveTools/eveapi#1]
can you finish off the example on how to call authed endpoints on the wiki? been trying to get it working but keep getting 

`Argument 1 passed to LaravelEveTools\EveApi\Jobs\Abstracts\AbstractAuthCharacterJob::__construct() must be an instance of LaravelEveTools\EveApi\Models\RefreshToken, string given`

is how im dispatching the job
```php

$token = RefreshToken::find($eve_data->id);
CharacterTitles::dispatchAfterResponse($eve_data->id, $token);
```

this is how the inside of my job looks

```php
namespace App\Jobs\Characters;

use LaravelEveTools\EveApi\Jobs\Characters\Titles;
use LaravelEveTools\EveApi\Models\RefreshToken;

use App\Models\Titles as CharacterTitle;


class CharacterTitles extends Titles
{

    public $queue = 'public'; //Override this to set a specific que

    protected $character_id;
    
    public function __construct(RefreshToken $token, $character_id)
    {
        parent::__construct($token);
        $this->character_id = $character_id;
    }

    public function handle()
    {
        $results = $this->retrieve();

        if(empty($results)) return;

        foreach($results as $result){
            $title = CharacterTitle::firstOrNew(['title_id' => $result->title_id]);
            $title->title_id = $result->title_id;
            $title->name = $result->name;
            $title->save();
        }

    }
}
```
TIA!

**Comment by mackenziexD** [comment]
looking into it ive got this thrown in my logs
`ccount(): Parameter must be an array or an object that implements Countable`

so i put it down to my scopes so im loading them like this
`
['publicData', 'esi-location.read_location.v1', ... ... ... ... ... ... ]
`

but now its throwing a Array to string conversion

**Comment by SimplyUnnamed** [comment]
```
$token = RefreshToken::find($eve_data->id);
CharacterTitles::dispatchAfterResponse($eve_data->id, $token);
```

Notice that you have provided the eve_data id as the first parameter, but your implementation has defined the RefreshToken as the first parameter.
